### ISSUE TITLE
Windfree AC Samsung

### ISSUE THREAD

**Issue by alexander19752409** [BobRak/OpenHAB-Smartthings#76] opened 2019-05-20 08:05 UTC
The system is connected, everything is displayed as described. Status information from the switch or temperature, I get synonymous. If I turn on the switch nothing happens, other commands do not work, even though they are green in Openhab.
I also see everything that should work in the Smartapp. Actually, you think everything is OK

Die Anlage ist verbunden, alles wird so wie beschrieben Angezeigt. Status Information vom Switch oder Temperatur bekomme ich auch. Schalte ich den Switch ein passiert nichts, andere commands funktionieren auch nicht, obwohl sie im Openhab grün sind.
Ich sehe in der Smartapp auch alles was funktionieren sollte. Eigentlich denkt man alles ist OK

**Comment by BobRak** [comment] 2019-05-20 15:47
The translation from German ti English is not that good so I am finding it difficult to understand what is wrong. It sounds like data is flowing from the Smartthings hub to openHAB but not the other direction. Is that correct?

Here are some things to check:

1. Verify that the mac address in the Device on the Smartthings app is correct.

2. Use the live logging on the Smartthings IDE to see if data is being sent to openHAB.

3. Check the openHAB logs for errors or messages that indicate a problem.

I will be leaving tomorrow and will have limited internet access until early June.

**Comment by alexander19752409** [comment] 2019-05-20 16:41
Yes, you are right.  Thank you very much for your effort.  My english is unfortunately bad

Am 20. Mai 2019 17:47:10 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by alexander19752409** [comment] 2019-05-20 17:14
Am 20. Mai 2019 17:47:10 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by BobRak** [comment] 2019-05-20 17:14
OK, thanks for getting back to me. I assume this is resolved and therefore I'm going to close the issue.

**Comment by alexander19752409** [comment] 2019-05-20 17:49
I mean you're right, data does not flow in the other direction.  Can I send you pictures of the configuration and the log?

**Comment by BobRak** [comment] 2019-05-20 21:44
I got the pictures you sent.

I'm not sure why there is no data in the smartthings log. After you opened that window did you change some settings in openhab so data should flow to the hub. And, change some devices connected to the hub so we should see some data being sent back to the openHAB server?

In your last picture I see an IP of 192.168.1.11. I'm not sure what this is but you configuration looks like the hub IP is 192.168.1.77, mac 08:52:a8:21:61:4c and the OpenHAB server is 192.168.1.10 with mac 0011328b20b1. Not sure what this ip of 192.168.1.11 is for.

Please in the paperui do: Configuration -> Things -> Smartthings Hub -> Edit (the circle with a pen in it). What is the IP and port show there? It should be 192.168.1.77 and port 39500

**Comment by alexander19752409** [comment] 2019-05-21 04:46
I sent pictures of the configuration via e-mail.  Thank you for the effort

**Comment by BobRak** [comment] 2019-05-21 15:37
In your latest set of pictures it looks like the ST Hub is in the inbox. Please look at the **Discovery** section of the README.md file. You should be configuring the hub and then discovery can discover the rest of the items.

You might also look at [issue #69](https://github.com/BobRak/OpenHAB-Smartthings/issues/69). This person is also running on a Diskstation.

Do you have other things connected to the ST hub and are they working?

Are you using the PaperUI to configure or are you convifuring with files?

Are there errors in the OpenHAB log file? Are you seeing the Smartthings binding getting loaded and communicating with the hub.

I leave within the next hour for the airport and will be away until the beginning of June. I will have some internet access but no access to my home computer.

**Comment by alexander19752409** [comment] 2019-05-25 03:25
Currently have only two air conditioners connected.  There are no errors in the openhab log.  I have already configured the hub with "paperui" and with the "Thinks" file, tested, does not work either.  69 I also read through.  I am using version 2.4 openhab.  Do you still need pictures to check my configuration?

Am 21. Mai 2019 17:37:32 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by BobRak** [comment] 2019-06-02 00:52
Hi @alexander19752409 
Sorry for the delay but I am now home and have access to my computer.

From what I've seen so far I am not seeing any evidence that the smartthings binding is getting loaded. Can you do the following:
1. stop openhab 
2. start a tail on the openhab.log file (in your openhab log dir)
3. start openhab
4. look for the following messages

```
2019-06-01 17:23:22.847 [DEBUG] [org.openhab.binding.smartthings     ] - BundleEvent STARTING - org.openhab.binding.smartthings
2019-06-01 17:23:23.038 [DEBUG] [org.openhab.binding.smartthings     ] - BundleEvent STARTED - org.openhab.binding.smartthings
2019-06-01 17:23:23.097 [DEBUG] [org.openhab.binding.smartthings     ] - ServiceEvent REGISTERED - {javax.servlet.ServletContext}={osgi.web.version=2.5.0.201904051837, osgi.web.contextpath=/, service.id=168, osgi.web.symbolicname=org.openhab.binding.smartthings, service.bundleid=208, service.scope=singleton, osgi.web.contextname=default} - org.openhab.binding.smartthings
2019-06-01 17:23:26.166 [DEBUG] [org.openhab.binding.smartthings     ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory, org.osgi.service.event.EventHandler}={service.id=219, service.bundleid=208, service.scope=bundle, event.topics=org/openhab/binding/smartthings/state, component.name=binding.smartthings, component.id=15} - org.openhab.binding.smartthings
2019-06-01 17:23:46.859 [DEBUG] [org.openhab.binding.smartthings     ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=307, service.bundleid=208, service.scope=singleton} - org.openhab.binding.smartthings
2019-06-01 17:23:46.866 [DEBUG] [org.openhab.binding.smartthings     ] - ServiceEvent REGISTERED - {org.osgi.service.event.EventHandler}={service.id=308, service.bundleid=208, service.scope=singleton, event.topics=org/openhab/binding/smartthings/discovery} - org.openhab.binding.smartthings
...

```

These messages indicate that the smartthings binding jar file was found in the addons directory and was loaded.  If you aren't seeing message like this then the smartthings binding hasn't been loaded. There are two possible causes of this. 1) The jar file couldn't be found or couldn't be loaded. Make sure the permissions are such that everyone has read and execute permission. 2) something else is wrong and in that case there sould be an error message indicating what the problem is.

After that you should see some messages like:

```
2019-01-27 16:41:04.834 [DEBUG] [iscovery.SmartthingsDiscoveryService] - Starting discovery scan on bridge smartthings:smartthings:04160446
2019-01-27 16:41:05.191 [INFO ] [hings.internal.SmartthingsHttpClient] - Sent message "{"discovery": "yes", "openHabStartTime": 1548636064857}" with path "/discovery" to the Smartthings hub, recieved HTTP status 202
2019-01-27 16:41:06.028 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthings servlet service() called with: 192.168.86.46: POST /smartthings/discovery
2019-01-27 16:41:06.032 [DEBUG] [rtthings.internal.SmartthingsServlet] - Smartthing servlet function requested: discovery with Method: POST

```

These indicate the smartthings discovery service has sent a message to the hub asking about the devices that are registered in the Smartthings OpenHabAppV2 app.

Please let me know about this.

**Comment by alexander19752409** [comment] 2019-12-24 05:32
hello good news, now the binding works in both directions.  What is still missing, I can not switch the device to cooling, heating, dehumidifying, wind direction, wind speed ... can I possibly still install it?

thank you very much and happy christmas and a happy new year



https://smartthings.developer.samsung.com/docs/api-ref/capabilities.html

Am 25. Mai 2019 05:25:08 MESZ schrieb Alexander Gerl <alexander.gerl@online.de>:

**Comment by BobRak** [comment] 2019-12-24 19:35
Hi Alexander:
Glad to hear you have made good progress. The reason that you can not change the device operating mode is because I have not included that capability in the binding. When I originally developed the binding a couple of years ago I included all of the capabilities from the Smartthings capabilities reference. Since that time Samsung has added probably 100 capabilities. I'll go back and look at adding some of them. The biggest problem in adding most of these capabilities is that I don't have the actual devices to test them on and make sure they work.  When I get a chance I'll work at adding a few, such as air conditioner, washer, dryer. I'll let you know when I have something you can try out.
Bob

**Comment by alexander19752409** [comment] 2019-12-24 22:54
I have no idea why it works but it works!  Thank you very much, I will be happy to test it.

Alexander 

Am 24. Dezember 2019 20:35:52 MEZ schrieb Bob Raker <notifications@github.com>:

**Comment by BobRak** [comment] 2020-01-10 04:58
Hi Alexander:
I am ready to see about adding some of the new capabilities to my openHAB app. Before I go to this considerable amount of work could you confirm that you have been able to connect your Samsung AC to the Smartthing CLASSIC app. Remember this binding only works with the classic app. 

If so, could you take a screenshot of the AC control page in your ST app on your phone? I want to see what the UI looks like and what the controls are.
Thanks
Bob

**Comment by alexander19752409** [comment] 2020-01-10 05:42
Thank you, the app is unfortunately in German

Am 10. Januar 2020 05:58:32 MEZ schrieb Bob Raker <notifications@github.com>:

**Comment by alexander19752409** [comment] 2020-02-19 09:38
just wanted to ask if they have progressed a bit?

regards

Alexander Gerl


Am 10. Januar 2020 05:58:32 MEZ schrieb Bob Raker <notifications@github.com>:

**Comment by BobRak** [comment] 2020-02-19 17:20
I've been working on trying to get Dryer data for another user. It has turned into a lot of work. First I had to build a simulator and then add the dryer to the openHAB device handlers. That is when I discovered the Capabilities document isn't correct. So, I am still working on that. At this point I only plan to finish the dryer. So at this point I have no plans to try to add the AC.

**Comment by alexander19752409** [comment] 2020-04-13 20:04
Is it possible to perform scenes using the binding?

Many thanks

Alexander Gerl


Am 19. Februar 2020 18:20:46 MEZ schrieb Bob Raker <notifications@github.com>:

**Comment by BobRak** [comment] 2020-04-14 04:25
I'm not all that familiar with the scenes capability. I just tried it out for the first time. Seems like it can control the switch but none of the other capabilities. I don't have any control of which capabilities that can be added to a scene.  Sorry, that is all I know.

Have you had a chance to install the updated binding and test? I am planning to submit this the openHAB soon for addition as a core binding. Any feedback you can provide would be helpful.

Bob

**Comment by alexander19752409** [comment] 2020-04-14 05:41
Everything is stored in a scene that I need for my air conditioning system, for example to switch it on.  The mode, temperature and level are set.  I should only be able to execute the scene, that will be the solution for me!  I may update and report smartthings this week.

Am 14. April 2020 06:25:54 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by alexander19752409** [comment] 2020-04-14 06:17
For the air conditioner 4 things are needed, temperature, mode (heating, ventilation, drying, cooling), on off, wind direction, pulls temperature.  I'm currently running the scenes via the alexa app, alexa i can control via openhab binding.  something very cumbersome but at least it works.

Am 14. April 2020 06:25:54 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by alexander19752409** [comment] 2020-04-14 08:27
The mode is now displayed in the string, how can I send it to the air conditioner?

Am 14. April 2020 10:17:41 MESZ schrieb Alexander Gerl <alexander.gerl@online.de>:

**Comment by BobRak** [comment] 2020-04-14 19:46
Alexander:

I have created a new Github Repo called SmartthingsSimulatedAirConditioner that contains sample config files. I particular have a look at the .items file. It shows how to send updates. I also created a AC simulator but I doubt you will find it helpful. [Here is a link.](https://github.com/BobRak/SmartthingsSimulatedAirConditioner)

As I mentioned earlier, I have implemented most of the capabilities in the Smartthings Capabilities doc. You can see that [doc here](https://docs.smartthings.com/en/latest/).  You can look in [this file](https://github.com/BobRak/OpenHAB-Smartthings/blob/master/org.openhab.binding.smartthings/src/main/resources/ESH-INF/thing/thing-types.xml). to see exactly what I have implemented. If you find something in the ST capabilities doc not in the thing-types file you can ask and I'll consider implementing it. At the same time I'm going to move ahead with submitting this to openHAB to be added to the system. 

Bob

**Comment by alexander19752409** [comment] 2020-04-15 06:59
where can I send you mail with pictures, it does not work on this address!

Am 14. April 2020 21:47:06 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by alexander19752409** [comment] 2020-04-15 07:07
how should i send the setting?  for example air conditioning fashion wind?

Am 14. April 2020 21:47:06 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by alexander19752409** [comment] 2020-04-15 07:08
Am 14. April 2020 21:47:06 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by alexander19752409** [comment] 2020-04-15 07:13
Everything is stored in a scene that I need for my air conditioning system, for example to switch it on.  The mode, temperature and level are set.  I should only be able to execute the scene, that will be the solution for me!  I may update and report smartthings this week.

Am 14. April 2020 21:47:06 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by alexander19752409** [comment] 2020-04-15 07:19
I am not sure which emails you have received from me!

Am 14. April 2020 21:47:06 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by alexander19752409** [comment] 2020-04-15 08:19
as in the picture below it should work

Am 14. April 2020 21:47:06 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by BobRak** [comment] 2020-04-15 15:18
I haven't received any emails from you. I would very much prefer that all communication be done through this website because it provides a record for me that I can sometimes use to answer questions from other users. You can send me pictures by copying a picture using a clipping/snipping tool to copy something to the clipboard and then pasting it into your message. You can also drag and drop files.

From openHAB there is no way to interact from scenes so if you want to use openHAB you will have to interact with the devices. Smartthings just doesn't provide a programmatic way to interact with scenes.

**Comment by alexander19752409** [comment] 2020-04-15 16:45
I sent them a lot, but unfortunately they received none of them.  unfortunately have no account in the forum

Am 15. April 2020 17:19:07 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by alexander19752409** [comment] 2020-04-15 16:49
![FJIMG_20200415_110416](https://user-images.githubusercontent.com/50801870/79364436-a4a77700-7f49-11ea-803b-78d54b58eb60.jpg)
![20200415_110406](https://user-images.githubusercontent.com/50801870/79364447-a7a26780-7f49-11ea-8f9f-14d5a9078217.jpg)
![FJIMG_20200415_091105](https://user-images.githubusercontent.com/50801870/79364461-ad984880-7f49-11ea-8f80-b381a5a4ef6e.jpg)
![FJIMG_20200415_085412](https://user-images.githubusercontent.com/50801870/79364470-af620c00-7f49-11ea-9b22-0eb6f46dfc53.jpg)
![FJIMG_20200415_085343](https://user-images.githubusercontent.com/50801870/79364486-b2f59300-7f49-11ea-8c7c-ea85c38824d0.jpg)
![FJIMG_20200415_085337](https://user-images.githubusercontent.com/50801870/79364496-b557ed00-7f49-11ea-919a-8b83fed2bd45.jpg)
![FJIMG_20200415_085331](https://user-images.githubusercontent.com/50801870/79364506-b8eb7400-7f49-11ea-8ec6-0f019126fad6.jpg)
![FJIMG_20200415_085319](https://user-images.githubusercontent.com/50801870/79364516-bdb02800-7f49-11ea-8dcc-c772331241fe.jpg)
![FJIMG_20200415_085305](https://user-images.githubusercontent.com/50801870/79364524-c0128200-7f49-11ea-8383-fd4151a0ca53.jpg)
![FJIMG_20200415_085255](https://user-images.githubusercontent.com/50801870/79364533-c1dc4580-7f49-11ea-8522-a8d6a09df234.jpg)

**Comment by alexander19752409** [comment] 2020-04-15 16:51
![FJIMG_20200415_085255](https://user-images.githubusercontent.com/50801870/79364802-20a1bf00-7f4a-11ea-819c-23320b212aef.jpg)

**Comment by alexander19752409** [comment] 2020-04-15 16:52
maybe that helps a little

**Comment by alexander19752409** [comment] 2020-04-15 16:57
only 5 functions are needed for the air conditioner, at the moment I am executing the scenes via the alexa app.  I can trigger the scenes via the alexa binding in openhab.

**Comment by alexander19752409** [comment] 2020-04-15 17:00
![FJIMG_20200415_085331](https://user-images.githubusercontent.com/50801870/79365761-598e6380-7f4b-11ea-80b5-00b710b0b859.jpg)

**Comment by alexander19752409** [comment] 2020-04-15 17:03
Supportedacmodes, airflowdirection,acfanmodes ,in oft, Temperatur

**Comment by BobRak** [comment] 2020-04-16 01:37
At this point I'm confused about what you want. As I told you earlier I support many of the capabilities in the Smartthings capability document [See it here](https://docs.smartthings.com/en/latest/capabilities-reference.html).  None of the capabilities listed immediately above are in the Capabilities Reference so I don't and can not support them. The Temperatur is close to Thermostat which I do support.

Here are how I setup the simulator for testing on my system using the simulated airconditioner that I created for testing

**things;**
```
    // This can be added to your .things file
    // Air Conditioner test
    switch                   SimulatedAcSwitch     [ smartthingsName="Simulated Air Conditioner" ]
    airConditionerMode       SimulatedAcMode       [ smartthingsName="Simulated Air Conditioner" ]
    temperatureMeasurement   SimulatedAcTemp       [ smartthingsName="Simulated Air Conditioner" ]
    thermostatCoolingSetpoint SimulatedAcSet       [ smartthingsName="Simulated Air Conditioner" ]
    thermostat                SimulatedAcTherm     [ smartthingsName="Simulated Air Conditioner" ]
    // Replace "Simulated Air Conditioner" in the the smartthingsName= file with the name you gave your AC in the Smarrthings App
    // Optionally replace the middle parameter (i.e. SimulatedAcSwiitch) with one of your choice and then change the .items file accordingly
```

**items:**
```
// This can be added to your .things file
Switch SimulatedAcSwitchItem   "Simulated Air conditioner Switch" <switch>             { channel="smartthings:switch:Home:SimulatedAcSwitch:switch" }
String SimulatedAcModeItem     "Simulated Air conditioner Mode [%s]"                   { channel="smartthings:airConditionerMode:Home:SimulatedAcMode:airConditionerMode" }
Number SimulatedAcTempItem     "Simulated Air conditioner Temperature [%d]"            { channel="smartthings:temperatureMeasurement:Home:SimulatedAcTemp:temperature" }
Number SimulatedAcSetItem      "Simulated Air conditioner Cooling Set [%d]" <slider>   { channel="smartthings:thermostatCoolingSetpoint:Home:SimulatedAcSet:coolingSetpoint" }
Number SimulatedAcThermItem    "Simulated AC Thermostat Cooling Set [%d]" <slider>   { channel="smartthings:thermostat:Home:SimulatedAcTherm:coolingSetpoint" }
// Change the second parameter (i.e. SimulatedAcSwitchItem) to match your .things file
// Change the descriptions if desired
// Change the channel= values to match your bridge and thing names

```
sitemaps
```
// Add this to your .sitemap file
    Frame label="Simulated Air Conditioner" {
        Switch item=SimulatedAcSwitchItem
        Switch item=SimulatedAcModeItem
        Text   item=SimulatedAcTempItem 
        Setpoint item=SimulatedAcSetItem minValue=20 maxValue=80 step=5
        Setpoint item=SimulatedAcThermItem minValue=20 maxValue=80 step=5
    }
// Change the item= values to match your items.
// Change the label if your want    

```

**Comment by alexander19752409** [comment] 2020-04-16 02:15
Switch item=SimulatedAcModeItem

String SimulatedAcModeItem "Simulated Air conditioner Mode [%s]" { channel="smartthings:airConditionerMode:Home:SimulatedAcMode:airConditionerMode" } 

how can I use it to switch from cooling to heating, for example?

need a selection menu


Am 16. April 2020 03:37:27 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by BobRak** [comment] 2020-04-17 17:47
Hi Alexander:

I've taken all of the commands that you have sent and am comparing them to what is in the Smartthings capability document. I am also testing all of the command to determine that they actually work. For instance the dryCool command does not work, at least for me. And, heat does nothing. There is a Thermostat capability ([click here](https://docs.smartthings.com/en/latest/capabilities-reference.html#thermostat)) and that includes both heat and cool and others, Can you try that and let me know.

I have an idea on how to make your set work and still keep the official Smartthings set. I'll be working on that.  I'll get something to you by early next week at the latest.

I hope you appreciate the amount of time and work this has taken me. It has certainly delayed me submitting it to openHAB for addition the product.

Bob

**Comment by alexander19752409** [comment] 2020-04-17 18:47
thanks for the effort, the air conditioning is actually not bad you can control it with openhab.  The problem with the thermostat it only works in automatic mode, if the mode was changed with the remote control, it does not work.  I always have to set everything correctly when switching on.  I will soon buy a new washing machine from miele and would also like to control it from openhab.  In Germany, because of the extremely high electricity price, many people have a solar system on the house roof, it is very important to use the energy when it is there, you can only do it if you can control the electricity guzzlers.  Miele itself has ordered a binding for its appliances.  the air conditioner needs about 2.5kW and the washing machine too, my solar system creates 6kW peak.  My electricity bill would be astronomical due to the air conditioning, it definitely makes sense to control it according to my solar system, the kwh in Germany costs 32 cents.  my thought is kind of an ecosystem.  Thanks a lot  .  Greetings from Allersberg near Nuremberg

Am 17. April 2020 19:47:46 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by BobRak** [comment] 2020-04-20 15:11
Hi Alexander:
I went through a more extensive testing of the AC and Thermostat related capabilities using a simulator Device Type that I created just for this purpose. Please let me know if things are better and if there are any states missing. It is impossible for me to do a really good test since I don't own any of the actual equipment.

You also asked about a selection menu. In your sitemap use the Selection option instead of switch where you need a menu. i.e.:
` Selection item=SimulatedAcModeItem`

**Comment by alexander19752409** [comment] 2020-04-20 16:40
I'm curious if it works, does smartthings work via the hub even without an internal connection?

Am 20. April 2020 17:11:27 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by alexander19752409** [comment] 2020-04-20 19:47
![Screenshot_20200420-214429_openHAB Beta](https://user-images.githubusercontent.com/50801870/79793243-84fcbe00-8350-11ea-9895-5023845be32e.jpg)

**Comment by alexander19752409** [comment] 2020-04-20 19:49
thank you very much, works great !!!!!  Great tip !!!!!  do you get the rest to run?

**Comment by alexander19752409** [comment] 2020-04-20 19:51
switch, mode, temperature now works !!

**Comment by alexander19752409** [comment] 2020-04-20 20:00
Now the fan speed and wind direction would be great, the rest is luxury!

**Comment by BobRak** [comment] 2020-04-21 02:29
Thanks for letting me know that things are better.  I think you might have some control over the fan with the "Thermostat Fan Mode" capability.

Did you select the Modes to be displayed using a Mapping in the sitemap.

Thanks,

Bob

**Comment by alexander19752409** [comment] 2020-04-21 04:37
I selected via the mapping in the sitemap.

Am 21. April 2020 04:29:33 MESZ schrieb Bob Raker <notifications@github.com>:

**Comment by alexander19752409** [comment] 2020-04-21 06:33
Thermostat Fan Mode tried, unfortunately does not work, you would have to get to the fan somehow!

**Comment by alexander19752409** [comment] 2020-04-21 06:36
![Uploading 20200421_083607.jpg…]()

**Comment by BobRak** [comment] 2020-04-22 03:30
Hi Alexander:

I went back and looked at the pictures you sent me. I see your AC supports a capability called Fan Mode. That isn't part of the Capabilities, at least for the Smartthings classic. Therefore there is nothing I can do. Sorry.  

Have you looked at and tried the Fan Speed capability? that would be my only other suggestion.

Bob

**Closed by BobRak** 2020-04-22 03:30 UTC

**Comment by alexander19752409** [comment] 2020-04-22 05:30
![Screenshot_20200422-072849_SmartThings](https://user-images.githubusercontent.com/50801870/79944116-0a749100-846b-11ea-808e-c6f133631a8d.jpg)

**Comment by alexander19752409** [comment] 2020-04-22 05:30
Too bad, there is fan mode in the standard app

**Comment by alexander19752409** [comment] 2020-04-22 05:48
![20200422_074750](https://user-images.githubusercontent.com/50801870/79945221-a3a4a700-846d-11ea-959d-b70fdff85f70.jpg)

**Comment by alexander19752409** [comment] 2020-04-22 05:49
unfortunately does not work, a real shame
